Load Balancer Simulation: src/Utils.cpp File Reference
Utils.cpp File Reference
Implementation of utility functions for generating random IP addresses and integers.
#include "Utils.h"
#include <random>
#include <sstream>
Functions
static std::mt19937 rng ((unsigned) time(nullptr))
Standard process used for generating random numbers, seeded with the current time.
std::string randomIp ()
Generates a randomized standard IPv4 address string.
int randBetween (int lo, int hi)
Generates a random integer within a specified inclusive range.
Detailed Description
Implementation of utility functions for generating random IP addresses and integers.
Definition in file Utils.cpp.
Function Documentation
randBetween()
int randBetween (int lo, int hi)
Generates a random integer within a specified inclusive range.
Parameters
lo The lower bound of the desired range (inclusive).
hi The upper bound of the desired range (inclusive).
Returns
A random integer between lo and hi.
Definition at line 34 of file Utils.cpp.
{
    std::uniform_int_distribution<int> d(lo, hi);
    return d(rng);
}
References rng().
Referenced by main(), and LoadBalancer::runSimulation().
randomIp()
std::string randomIp ()
Generates a randomized standard IPv4 address string.
Creates four random integers between 0 and 255 and formats them into a standard dot-decimal notation IP address string.
Returns
A string formatted as "X.X.X.X".
Definition at line 21 of file Utils.cpp.
                     {
    std::uniform_int_distribution<int> d(0,255);
    std::ostringstream ss;
    ss << d(rng) << '.' << d(rng) << '.' << d(rng) << '.' << d(rng);
    return ss.str();
}
References rng().
Referenced by main(), and LoadBalancer::runSimulation().
rng()
std::mt19937 rng ((unsigned) time(nullptr)) static
Standard process used for generating random numbers, seeded with the current time.
Referenced by randBetween(), and randomIp().