Load Balancer Simulation: Logger Class Reference
Logger Class Reference
Thread-safe logging utility for writing simulation events to an output file.
#include <Logger.h>
Public Member Functions
Logger ()=default
Default constructor.
~Logger ()
Destructor, ensures the file stream is safely closed.
bool open (const std::string &filename)
Opens a file stream for logging.
void close ()
Safely closes the active log file stream.
void log (const std::string &s)
Writes a string message to the log file in a thread-safe manner.
void logConsole (const std::string &s, const std::string &ansiColor="")
Convenience method to print a colored log message directly to the console.
Private Attributes
std::ofstream ofs
File output stream for writing log data.
std::mutex m
Mutex ensuring thread-safe logging operations.
Detailed Description
Thread-safe logging utility for writing simulation events to an output file.
Definition at line 17 of file Logger.h.
Constructor & Destructor Documentation
Logger()
Logger::Logger () default
Default constructor.
~Logger()
Logger::~Logger ()
Destructor, ensures the file stream is safely closed.
Destructor for the Logger class. Ensures that the underlying file stream is safely closed upon destruction.
Definition at line 13 of file Logger.cpp.
{ close(); }
References close().
Member Function Documentation
close()
void Logger::close ()
Safely closes the active log file stream.
Safely closes the active log file stream if it is currently open.
Definition at line 28 of file Logger.cpp.
                   {
    if (ofs.is_open()) {
        ofs.close();
    }
}
References ofs.
Referenced by main(), and ~Logger().
log()
void Logger::log (const std::string & s)
Writes a string message to the log file in a thread-safe manner.
Writes a string message to the log file in a thread-safe manner. Uses a mutex lock to ensure that concurrent log calls do not interleave data.
Parameters
s The message string to log.
s The message string to be logged.
Definition at line 39 of file Logger.cpp.
{
    std::lock_guard<std::mutex> lk(m);
    if (ofs.is_open()) {
        ofs << s << std::endl;
    }
}
References m, and ofs.
Referenced by main().
logConsole()
void Logger::logConsole (const std::string & s, const std::string & ansiColor = "")
Convenience method to print a colored log message directly to the console.
Parameters
s The message string to output.
ansiColor The raw ANSI color code sequence to format the string.
open()
bool Logger::open (const std::string & filename)
Opens a file stream for logging.
Parameters
filename The path and name of the file to open.
Returns
true if the file was successfully opened, false otherwise.
Definition at line 20 of file Logger.cpp.
{
    ofs.open(filename);
    return ofs.is_open();
}
References ofs.
Referenced by main().
Member Data Documentation
m
std::mutex Logger::m private
Mutex ensuring thread-safe logging operations.
Definition at line 56 of file Logger.h.
Referenced by log().
ofs
std::ofstream Logger::ofs private
File output stream for writing log data.
Definition at line 55 of file Logger.h.
Referenced by close(), log(), and open().
The documentation for this class was generated from the following files:
include/Logger.h
src/Logger.cpp