Load Balancer Simulation: Configuration Class Reference
Configuration Class Reference
Parses and stores configuration key-value pairs from a text file.
#include <Configuration.h>
Public Member Functions
Configuration ()=default
Default constructor.
bool loadFromFile (const std::string &path)
Loads and parses key-value pairs from the specified file path.
std::string getString (const std::string &key, const std::string &def="") const
Retrieves a string configuration value.
int getInt (const std::string &key, int def) const
Retrieves an integer configuration value.
Private Attributes
std::map< std::string, std::string > values
Map storing the raw key-value pairs.
Detailed Description
Parses and stores configuration key-value pairs from a text file.
Definition at line 27 of file Configuration.h.
Constructor & Destructor Documentation
Configuration()
Configuration::Configuration () default
Default constructor.
Member Function Documentation
getInt()
int Configuration::getInt (const std::string & key, int def) const
Retrieves an integer configuration value.
Parameters
key The configuration key to look up.
def The default integer value to return if the key is not found.
Returns
The integer value associated with the key, or the default value.
Attempts to parse the string value associated with the given key into an integer. If the key does not exist or the string cannot be parsed as an integer, the default value is returned.
Parameters
key The configuration key to look up.
def The default integer value to return if the key is not found or parsing fails.
Returns
The integer value associated with the key, or the provided default value.
Definition at line 67 of file Configuration.cpp.
{
    auto s = getString(key, "");
    if (s.empty()) {
        return def;
    }
    try {
        return std::stoi(s);
    }
    catch(...) {
        return def;
    }
}
References getString().
Referenced by main().
getString()
std::string Configuration::getString (const std::string & key, const std::string & def = "") const
Retrieves a string configuration value.
Parameters
key The configuration key to look up.
def The default value to return if the key is not found.
Returns
The string value associated with the key, or the default value.
Parameters
key The configuration key to look up.
def The default value to return if the key is not found in the configuration.
Returns
The string value associated with the key, or the provided default value if not found.
Definition at line 50 of file Configuration.cpp.
{
    auto it = values.find(key);
    if (it == values.end()) {
        return def;
    }
    return it->second;
}
References values.
Referenced by getInt(), LoadBalancer::LoadBalancer(), and main().
loadFromFile()
bool Configuration::loadFromFile (const std::string & path)
Loads and parses key-value pairs from the specified file path.
Parameters
path The filesystem path to the config file.
Returns
true if the file was loaded and parsed successfully, false otherwise.
Reads the file line by line, ignores comments starting with '#', and extracts key-value pairs separated by '='. Populates the internal map with these pairs.
Parameters
path The filesystem path to the config file to be loaded.
Returns
true if the file was successfully opened and parsed, false otherwise.
Definition at line 17 of file Configuration.cpp.
{
    std::ifstream in(path);
    if (!in.is_open()) {
        return false;
    }
    std::string line;
    while (std::getline(in, line)) {
        auto comment = line.find('#');
        if (comment != std::string::npos){
            line = line.substr(0, comment);
        }
        std::istringstream iss(line);
        std::string kv;
        if (!(iss >> kv)){
            continue;
        }
        auto eq = kv.find('=');
        if (eq == std::string::npos){
            continue;
        }
        std::string k = kv.substr(0, eq);
        std::string v = kv.substr(eq+1);
        values[k] = v;
    }
    return true;
}
References values.
Referenced by main().
Member Data Documentation
values
std::map<std::string, std::string> Configuration::values private
Map storing the raw key-value pairs.
Definition at line 58 of file Configuration.h.
Referenced by getString(), and loadFromFile().
The documentation for this class was generated from the following files:
include/Configuration.h
src/Configuration.cpp